### ISSUE TITLE
FLAC?

### ISSUE THREAD

**Issue by tordenflesk** [kaiekaie/spencerhertz#1]
Hei. Er det virkelig nødvendig med FLAC? originalene er 128 AAC. Jeg vet at Youtube-DL henter det ned som .m4a

Var også nødt til å endre link 15 til:

.output(`./output/${data.title.replace(" ", "")}.flac`)

pga "TypeError: data.title.replaceAll is not a function"

sikkert pga min gamle versjon av Node

**Comment by kaiekaie** [comment]
Hei du kan endre til acc og .mp3 eller .m4v, ja replaceAll er ny node
feature. jeg har node version 16

tir. 14. sep. 2021 kl. 16:20 skrev tordenflesk ***@***.***>:

**Comment by tordenflesk** [comment]
Ja, tester flg. nå, og filene er tilsynelatende identiske med Yotuube-DL.

      .output(`./output/${data.title.replace(" ", "")}.m4a`)
      .audioCodec("aac")

finfint skript :)

**Comment by tordenflesk** [comment]
Fint hvis skriptet også kunne huske/hoppe over eksisterende nedlatinger, så slipper man å laste ned hele Papaya hver gang man kjører skriptet.

**Comment by kaiekaie** [comment]
Done!
