### ISSUE TITLE
"rename example.env til .env og fyll inn Variablen" ikke mulig på Windows

### ISSUE THREAD

**Issue by tordenflesk** [kaiekaie/spencerhertz#3]
Ikke mulig i Explorer, kun via 7-zip og lignende.

**Comment by kaiekaie** [comment]
Det skal bare være å endre navn på example.env til .env, hvis du ikke ser den må du vise skjulte filer i Windows:
https://support.microsoft.com/en-us/windows/show-hidden-files-0320fe58-0117-fd59-6851-9b7f9840fdb2

**Comment by tordenflesk** [comment]
Joda, ser fila. Men dersom man forsøker å endre navn på en fil via Windows Explorer så får man feilmelding om at filen må ha et navn. Denne begrensning har man ikke dersom man endrer navn via f.eks. 7-Zip.

**Comment by kaiekaie** [comment]
Riktig jeg endret filtypen til config.txt så det skal bli lettere

**Comment by kaiekaie** [comment]
skiftet filformat for config fil
